import { Store, Product } from './types';

export const stores: Store[] = [
  {
    id: '1',
    name: 'Carrefour',
    logo: '🛒',
    averageDeliveryTime: 35,
    deliveryFee: 5.00,
    minimumOrder: 30.00,
  },
  {
    id: '2',
    name: 'Spinneys',
    logo: '🏪',
    averageDeliveryTime: 40,
    deliveryFee: 7.00,
    minimumOrder: 40.00,
  },
  {
    id: '3',
    name: 'Lulu Hypermarket',
    logo: '🏬',
    averageDeliveryTime: 45,
    deliveryFee: 5.00,
    minimumOrder: 25.00,
  },
  {
    id: '4',
    name: 'Waitrose',
    logo: '🛍️',
    averageDeliveryTime: 50,
    deliveryFee: 10.00,
    minimumOrder: 50.00,
  },
  {
    id: '5',
    name: 'Choithrams',
    logo: '🏪',
    averageDeliveryTime: 30,
    deliveryFee: 5.00,
    minimumOrder: 35.00,
  },
];

export const products: Product[] = [
  { id: '1', storeId: '1', name: 'Milk', category: 'Dairy', brand: 'Almarai', price: 8.50, unit: '1L', inStock: true },
  { id: '2', storeId: '1', name: 'Bread', category: 'Bakery', brand: 'Modern Bakery', price: 4.00, unit: '400g', inStock: true },
  { id: '3', storeId: '1', name: 'Eggs', category: 'Dairy', brand: 'Al Jazira', price: 12.00, unit: '12 pieces', inStock: true },
  { id: '4', storeId: '1', name: 'Chicken Breast', category: 'Meat', brand: 'Al Watania', price: 24.50, unit: '1kg', inStock: true },
  { id: '5', storeId: '1', name: 'Tomatoes', category: 'Vegetables', price: 6.00, unit: '1kg', inStock: true },
  { id: '6', storeId: '1', name: 'Rice', category: 'Grains', brand: 'Mahmood', price: 35.00, unit: '5kg', inStock: true },
  { id: '7', storeId: '1', name: 'Olive Oil', category: 'Cooking', brand: 'Borges', price: 28.00, unit: '1L', inStock: true },
  { id: '8', storeId: '1', name: 'Yogurt', category: 'Dairy', brand: 'Almarai', price: 6.50, unit: '500g', inStock: true },
  { id: '9', storeId: '1', name: 'Bananas', category: 'Fruits', price: 7.00, unit: '1kg', inStock: true },
  { id: '10', storeId: '1', name: 'Orange Juice', category: 'Beverages', brand: 'Al Ain', price: 10.00, unit: '1L', inStock: true },

  { id: '11', storeId: '2', name: 'Milk', category: 'Dairy', brand: 'Almarai', price: 9.00, unit: '1L', inStock: true },
  { id: '12', storeId: '2', name: 'Bread', category: 'Bakery', brand: 'Modern Bakery', price: 4.50, unit: '400g', inStock: true },
  { id: '13', storeId: '2', name: 'Eggs', category: 'Dairy', brand: 'Al Jazira', price: 13.00, unit: '12 pieces', inStock: true },
  { id: '14', storeId: '2', name: 'Chicken Breast', category: 'Meat', brand: 'Al Watania', price: 26.00, unit: '1kg', inStock: true },
  { id: '15', storeId: '2', name: 'Tomatoes', category: 'Vegetables', price: 6.50, unit: '1kg', inStock: true },
  { id: '16', storeId: '2', name: 'Rice', category: 'Grains', brand: 'Mahmood', price: 33.00, unit: '5kg', inStock: true },
  { id: '17', storeId: '2', name: 'Olive Oil', category: 'Cooking', brand: 'Borges', price: 30.00, unit: '1L', inStock: true },
  { id: '18', storeId: '2', name: 'Yogurt', category: 'Dairy', brand: 'Almarai', price: 7.00, unit: '500g', inStock: true },
  { id: '19', storeId: '2', name: 'Bananas', category: 'Fruits', price: 8.00, unit: '1kg', inStock: true },
  { id: '20', storeId: '2', name: 'Orange Juice', category: 'Beverages', brand: 'Al Ain', price: 11.00, unit: '1L', inStock: true },

  { id: '21', storeId: '3', name: 'Milk', category: 'Dairy', brand: 'Almarai', price: 8.00, unit: '1L', inStock: true },
  { id: '22', storeId: '3', name: 'Bread', category: 'Bakery', brand: 'Modern Bakery', price: 3.75, unit: '400g', inStock: true },
  { id: '23', storeId: '3', name: 'Eggs', category: 'Dairy', brand: 'Al Jazira', price: 11.50, unit: '12 pieces', inStock: true },
  { id: '24', storeId: '3', name: 'Chicken Breast', category: 'Meat', brand: 'Al Watania', price: 23.00, unit: '1kg', inStock: true },
  { id: '25', storeId: '3', name: 'Tomatoes', category: 'Vegetables', price: 5.50, unit: '1kg', inStock: true },
  { id: '26', storeId: '3', name: 'Rice', category: 'Grains', brand: 'Mahmood', price: 32.00, unit: '5kg', inStock: true },
  { id: '27', storeId: '3', name: 'Olive Oil', category: 'Cooking', brand: 'Borges', price: 27.00, unit: '1L', inStock: true },
  { id: '28', storeId: '3', name: 'Yogurt', category: 'Dairy', brand: 'Almarai', price: 6.25, unit: '500g', inStock: true },
  { id: '29', storeId: '3', name: 'Bananas', category: 'Fruits', price: 6.50, unit: '1kg', inStock: true },
  { id: '30', storeId: '3', name: 'Orange Juice', category: 'Beverages', brand: 'Al Ain', price: 9.50, unit: '1L', inStock: true },

  { id: '31', storeId: '4', name: 'Milk', category: 'Dairy', brand: 'Organic Valley', price: 12.00, unit: '1L', inStock: true },
  { id: '32', storeId: '4', name: 'Bread', category: 'Bakery', brand: 'Artisan Bakery', price: 6.00, unit: '400g', inStock: true },
  { id: '33', storeId: '4', name: 'Eggs', category: 'Dairy', brand: 'Free Range', price: 18.00, unit: '12 pieces', inStock: true },
  { id: '34', storeId: '4', name: 'Chicken Breast', category: 'Meat', brand: 'Organic', price: 32.00, unit: '1kg', inStock: true },
  { id: '35', storeId: '4', name: 'Tomatoes', category: 'Vegetables', price: 8.00, unit: '1kg', inStock: true },
  { id: '36', storeId: '4', name: 'Rice', category: 'Grains', brand: 'Basmati Premium', price: 45.00, unit: '5kg', inStock: true },
  { id: '37', storeId: '4', name: 'Olive Oil', category: 'Cooking', brand: 'Extra Virgin', price: 38.00, unit: '1L', inStock: true },
  { id: '38', storeId: '4', name: 'Yogurt', category: 'Dairy', brand: 'Greek Style', price: 9.00, unit: '500g', inStock: true },
  { id: '39', storeId: '4', name: 'Bananas', category: 'Fruits', price: 9.00, unit: '1kg', inStock: true },
  { id: '40', storeId: '4', name: 'Orange Juice', category: 'Beverages', brand: 'Freshly Squeezed', price: 14.00, unit: '1L', inStock: true },

  { id: '41', storeId: '5', name: 'Milk', category: 'Dairy', brand: 'Almarai', price: 8.75, unit: '1L', inStock: true },
  { id: '42', storeId: '5', name: 'Bread', category: 'Bakery', brand: 'Modern Bakery', price: 4.25, unit: '400g', inStock: true },
  { id: '43', storeId: '5', name: 'Eggs', category: 'Dairy', brand: 'Al Jazira', price: 12.50, unit: '12 pieces', inStock: true },
  { id: '44', storeId: '5', name: 'Chicken Breast', category: 'Meat', brand: 'Al Watania', price: 25.00, unit: '1kg', inStock: true },
  { id: '45', storeId: '5', name: 'Tomatoes', category: 'Vegetables', price: 5.75, unit: '1kg', inStock: true },
  { id: '46', storeId: '5', name: 'Rice', category: 'Grains', brand: 'Mahmood', price: 34.00, unit: '5kg', inStock: true },
  { id: '47', storeId: '5', name: 'Olive Oil', category: 'Cooking', brand: 'Borges', price: 29.00, unit: '1L', inStock: true },
  { id: '48', storeId: '5', name: 'Yogurt', category: 'Dairy', brand: 'Almarai', price: 6.75, unit: '500g', inStock: true },
  { id: '49', storeId: '5', name: 'Bananas', category: 'Fruits', price: 7.50, unit: '1kg', inStock: true },
  { id: '50', storeId: '5', name: 'Orange Juice', category: 'Beverages', brand: 'Al Ain', price: 10.50, unit: '1L', inStock: true },
];
